
import ROOT as rt
from helpers.plotting_functions import sortHists


rt.TH1.SetDefaultSumw2(rt.kTRUE)
rt.gStyle.SetOptStat(0)

detvars = ["LYAtt", "LYDown", "LYRayleigh", "recomb2", "SCE", "wiremodThetaXZ", "wiremodThetaYZ", "wiremodX", "wiremodYZ"]

outfile = rt.TFile("systematics/detvar/CCnumu_particle_score_shifts_test/plots.root","RECREATE")


for detvar in detvars:
  f = rt.TFile("systematics/detvar/CCnumu_particle_score_shifts_test/calculate_detvar_systematics_CCnumu_particle_score_shifts_%s_output.root"%detvar, "READ")
  outfile.cd()
  h_muS_CV = f.Get("h_muS_CV")
  h_muS_var = f.Get("h_muS_var")
  h_muS_CV.SetLineColor(rt.kBlue)
  h_muS_CV.SetLineWidth(2)
  h_muS_var.SetLineColor(rt.kRed)
  h_muS_var.SetLineWidth(2)
  hists_muS = sortHists([h_muS_CV,h_muS_var])
  cnv_muS = rt.TCanvas("cnv_muS_%s"%detvar,"cnv_muS_%s"%detvar)
  hists_muS[0].Draw("EHIST")
  hists_muS[1].Draw("EHISTSAME")
  leg_muS = rt.TLegend(0.7,0.7,0.9,0.9)
  leg_muS.AddEntry(h_muS_CV, "CV", "l")
  leg_muS.AddEntry(h_muS_var, detvar, "l")
  leg_muS.Draw()
  cnv_muS.Write()
  h_muEC = f.Get("h_muEC")
  h_muEC.GetXaxis().SetRangeUser(-1,1)
  cnv_muEC = rt.TCanvas("cnv_muEC_%s"%detvar,"cnv_muEC_%s"%detvar)
  h_muEC.Draw("EHIST")
  cnv_muEC.SetLogy()
  cnv_muEC.Write()
  h_piS_CV = f.Get("h_piS_CV")
  h_piS_var = f.Get("h_piS_var")
  h_piS_CV.SetLineColor(rt.kBlue)
  h_piS_CV.SetLineWidth(2)
  h_piS_var.SetLineColor(rt.kRed)
  h_piS_var.SetLineWidth(2)
  hists_piS = sortHists([h_piS_CV,h_piS_var])
  cnv_piS = rt.TCanvas("cnv_piS_%s"%detvar,"cnv_piS_%s"%detvar)
  hists_piS[0].Draw("EHIST")
  hists_piS[1].Draw("EHISTSAME")
  leg_piS = rt.TLegend(0.7,0.7,0.9,0.9)
  leg_piS.AddEntry(h_piS_CV, "CV", "l")
  leg_piS.AddEntry(h_piS_var, detvar, "l")
  leg_piS.Draw()
  cnv_piS.Write()
  h_piEC = f.Get("h_piEC")
  h_piEC.GetXaxis().SetRangeUser(-1,1)
  cnv_piEC = rt.TCanvas("cnv_piEC_%s"%detvar,"cnv_piEC_%s"%detvar)
  h_piEC.Draw("EHIST")
  cnv_piEC.SetLogy()
  cnv_piEC.Write()
  h_prS_CV = f.Get("h_prS_CV")
  h_prS_var = f.Get("h_prS_var")
  h_prS_CV.SetLineColor(rt.kBlue)
  h_prS_CV.SetLineWidth(2)
  h_prS_var.SetLineColor(rt.kRed)
  h_prS_var.SetLineWidth(2)
  hists_prS = sortHists([h_prS_CV,h_prS_var])
  cnv_prS = rt.TCanvas("cnv_prS_%s"%detvar,"cnv_prS_%s"%detvar)
  hists_prS[0].Draw("EHIST")
  hists_prS[1].Draw("EHISTSAME")
  leg_prS = rt.TLegend(0.7,0.7,0.9,0.9)
  leg_prS.AddEntry(h_prS_CV, "CV", "l")
  leg_prS.AddEntry(h_prS_var, detvar, "l")
  leg_prS.Draw()
  cnv_prS.Write()
  h_prEC = f.Get("h_prEC")
  h_prEC.GetXaxis().SetRangeUser(-1,1)
  cnv_prEC = rt.TCanvas("cnv_prEC_%s"%detvar,"cnv_prEC_%s"%detvar)
  h_prEC.Draw("EHIST")
  cnv_prEC.SetLogy()
  cnv_prEC.Write()
  h_piD_CV = f.Get("h_piD_CV")
  h_piD_var = f.Get("h_piD_var")
  h_piD_CV.SetLineColor(rt.kBlue)
  h_piD_CV.SetLineWidth(2)
  h_piD_var.SetLineColor(rt.kRed)
  h_piD_var.SetLineWidth(2)
  hists_piD = sortHists([h_piD_CV,h_piD_var])
  cnv_piD = rt.TCanvas("cnv_piD_%s"%detvar,"cnv_piD_%s"%detvar)
  hists_piD[0].Draw("EHIST")
  hists_piD[1].Draw("EHISTSAME")
  leg_piD = rt.TLegend(0.7,0.7,0.9,0.9)
  leg_piD.AddEntry(h_piD_CV, "CV", "l")
  leg_piD.AddEntry(h_piD_var, detvar, "l")
  leg_piD.Draw()
  cnv_piD.Write()
  h_prD_CV = f.Get("h_prD_CV")
  h_prD_var = f.Get("h_prD_var")
  h_prD_CV.SetLineColor(rt.kBlue)
  h_prD_CV.SetLineWidth(2)
  h_prD_var.SetLineColor(rt.kRed)
  h_prD_var.SetLineWidth(2)
  hists_prD = sortHists([h_prD_CV,h_prD_var])
  cnv_prD = rt.TCanvas("cnv_prD_%s"%detvar,"cnv_prD_%s"%detvar)
  hists_prD[0].Draw("EHIST")
  hists_prD[1].Draw("EHISTSAME")
  leg_prD = rt.TLegend(0.7,0.7,0.9,0.9)
  leg_prD.AddEntry(h_prD_CV, "CV", "l")
  leg_prD.AddEntry(h_prD_var, detvar, "l")
  leg_prD.Draw()
  cnv_prD.Write()



