
import ROOT as rt
from helpers.plotting_functions import sortHists, getOverflowLabel, getDefaultValueLabel
from array import array

f = rt.TFile("plot_CCinclusive_selections_efficiency_and_purity_makeHists_output.root")
h_nue_eff_foundVtx = f.Get("h_nue_eff_foundVtx")
hT_nue_eff_foundVtx = f.Get("hT_nue_eff_foundVtx")
h_nue_pur_foundVtx = f.Get("h_nue_pur_foundVtx")
h_nue_eff_foundNuVtx = f.Get("h_nue_eff_foundNuVtx")
hT_nue_eff_foundNuVtx = f.Get("hT_nue_eff_foundNuVtx")
h_nue_pur_foundNuVtx = f.Get("h_nue_pur_foundNuVtx")
h_nue_eff_noMu = f.Get("h_nue_eff_noMu")
hT_nue_eff_noMu = f.Get("hT_nue_eff_noMu")
h_nue_pur_noMu = f.Get("h_nue_pur_noMu")
h_nue_eff_primEl = f.Get("h_nue_eff_primEl")
hT_nue_eff_primEl = f.Get("hT_nue_eff_primEl")
h_nue_pur_primEl = f.Get("h_nue_pur_primEl")
h_nue_eff_noMuLike = f.Get("h_nue_eff_noMuLike")
hT_nue_eff_noMuLike = f.Get("hT_nue_eff_noMuLike")
h_nue_pur_noMuLike = f.Get("h_nue_pur_noMuLike")
h_nue_eff_allCuts = f.Get("h_nue_eff_allCuts")
hT_nue_eff_allCuts = f.Get("hT_nue_eff_allCuts")
h_nue_pur_allCuts = f.Get("h_nue_pur_allCuts")
h_numu_eff_foundVtx = f.Get("h_numu_eff_foundVtx")
hT_numu_eff_foundVtx = f.Get("hT_numu_eff_foundVtx")
h_numu_pur_foundVtx = f.Get("h_numu_pur_foundVtx")
h_numu_eff_foundNuVtx = f.Get("h_numu_eff_foundNuVtx")
hT_numu_eff_foundNuVtx = f.Get("hT_numu_eff_foundNuVtx")
h_numu_pur_foundNuVtx = f.Get("h_numu_pur_foundNuVtx")
h_numu_eff_allCuts = f.Get("h_numu_eff_allCuts")
hT_numu_eff_allCuts = f.Get("hT_numu_eff_allCuts")
h_numu_pur_allCuts = f.Get("h_numu_pur_allCuts")
h_nue_sig_noCuts = f.Get("h_nue_sig_noCuts")
h_nue_sig_foundVtx = f.Get("h_nue_sig_foundVtx")
h_nue_sig_foundNuVtx = f.Get("h_nue_sig_foundNuVtx")
h_nue_sig_noMu = f.Get("h_nue_sig_noMu")
h_nue_sig_primEl = f.Get("h_nue_sig_primEl")
h_nue_sig_noMuLike = f.Get("h_nue_sig_noMuLike")
h_nue_sig_confPrimEl = f.Get("h_nue_sig_confPrimEl")
h_nue_sig_allCuts = f.Get("h_nue_sig_allCuts")
h_nue_bkg_foundVtx = f.Get("h_nue_bkg_foundVtx")
h_nue_bkg_foundNuVtx = f.Get("h_nue_bkg_foundNuVtx")
h_nue_bkg_noMu = f.Get("h_nue_bkg_noMu")
h_nue_bkg_primEl = f.Get("h_nue_bkg_primEl")
h_nue_bkg_noMuLike = f.Get("h_nue_bkg_noMuLike")
h_nue_bkg_confPrimEl = f.Get("h_nue_bkg_confPrimEl")
h_nue_bkg_allCuts = f.Get("h_nue_bkg_allCuts")
h_numu_sig_noCuts = f.Get("h_numu_sig_noCuts")
h_numu_sig_foundVtx = f.Get("h_numu_sig_foundVtx")
h_numu_sig_foundNuVtx = f.Get("h_numu_sig_foundNuVtx")
h_numu_sig_allCuts = f.Get("h_numu_sig_allCuts")
h_numu_bkg_foundVtx = f.Get("h_numu_bkg_foundVtx")
h_numu_bkg_foundNuVtx = f.Get("h_numu_bkg_foundNuVtx")
h_numu_bkg_allCuts = f.Get("h_numu_bkg_allCuts")

h_nue_eff_foundVtx.GetXaxis().SetRangeUser(0,1.9999)
h_nue_eff_foundVtx.GetYaxis().SetRangeUser(0,1.02)
h_nue_eff_foundVtx.GetXaxis().SetTitle("reconstructed neutrino energy (GeV)")
h_nue_eff_foundVtx.GetXaxis().CenterTitle(True)
h_nue_eff_foundVtx.GetYaxis().SetTitle("efficiency")
h_nue_eff_foundVtx.SetTitle("Inclusive CC #nu_{e} Selection Efficiency Predictions")

hT_nue_eff_foundVtx.GetYaxis().SetRangeUser(0,1.0)
hT_nue_eff_foundVtx.GetXaxis().SetTitle("true neutrino energy (GeV)")
hT_nue_eff_foundVtx.GetXaxis().CenterTitle(True)
hT_nue_eff_foundVtx.GetYaxis().SetTitle("efficiency")
hT_nue_eff_foundVtx.SetTitle("Inclusive CC #nu_{e} Selection Efficiency Predictions")

h_nue_pur_foundVtx.GetXaxis().SetRangeUser(0,1.9999)
h_nue_pur_foundVtx.GetYaxis().SetRangeUser(0,1.02)
h_nue_pur_foundVtx.GetXaxis().SetTitle("reconstructed neutrino energy (GeV)")
h_nue_pur_foundVtx.GetXaxis().CenterTitle(True)
h_nue_pur_foundVtx.GetYaxis().SetTitle("purity")
h_nue_pur_foundVtx.SetTitle("Inclusive CC #nu_{e} Selection Purity Predictions")

h_numu_eff_foundVtx.GetXaxis().SetRangeUser(0,1.8999)
h_numu_eff_foundVtx.GetYaxis().SetRangeUser(0,1.02)
h_numu_eff_foundVtx.GetXaxis().SetTitle("reconstructed neutrino energy (GeV)")
h_numu_eff_foundVtx.GetXaxis().CenterTitle(True)
h_numu_eff_foundVtx.GetYaxis().SetTitle("efficiency")
h_numu_eff_foundVtx.SetTitle("Inclusive CC #nu_{#mu} Selection Efficiency Predictions")

hT_numu_eff_foundVtx.GetYaxis().SetRangeUser(0,1.0)
hT_numu_eff_foundVtx.GetXaxis().SetTitle("true neutrino energy (GeV)")
hT_numu_eff_foundVtx.GetXaxis().CenterTitle(True)
hT_numu_eff_foundVtx.GetYaxis().SetTitle("efficiency")
hT_numu_eff_foundVtx.SetTitle("Inclusive CC #nu_{#mu} Selection Efficiency Predictions")

h_numu_pur_foundVtx.GetXaxis().SetRangeUser(0,1.8999)
h_numu_pur_foundVtx.GetYaxis().SetRangeUser(0,1.02)
h_numu_pur_foundVtx.GetXaxis().SetTitle("reconstructed neutrino energy (GeV)")
h_numu_pur_foundVtx.GetXaxis().CenterTitle(True)
h_numu_pur_foundVtx.GetYaxis().SetTitle("purity")
h_numu_pur_foundVtx.SetTitle("Inclusive CC #nu_{#mu} Selection Purity Predictions")

h_nue_sig_foundVtx.GetXaxis().SetRangeUser(0,1.9999)
h_nue_sig_foundVtx.GetYaxis().SetRangeUser(0,15)
h_nue_sig_foundVtx.GetXaxis().SetTitle("reconstructed neutrino energy (GeV)")
h_nue_sig_foundVtx.GetXaxis().CenterTitle(True)
h_nue_sig_foundVtx.GetYaxis().SetTitle("events per 4.4e+19 POT")
h_nue_sig_foundVtx.SetTitle("Selected Inclusive CC #nu_{e} Signal Predictions")

h_nue_bkg_foundVtx.GetXaxis().SetRangeUser(0,1.9999)
h_nue_bkg_foundVtx.GetYaxis().SetRangeUser(0.004,10000000)
h_nue_bkg_foundVtx.GetXaxis().SetTitle("reconstructed neutrino energy (GeV)")
h_nue_bkg_foundVtx.GetXaxis().CenterTitle(True)
h_nue_bkg_foundVtx.GetYaxis().SetTitle("events per 4.4e+19 POT")
h_nue_bkg_foundVtx.SetTitle("Selected Inclusive CC #nu_{e} Background Predictions")

h_numu_sig_foundVtx.GetXaxis().SetRangeUser(0,1.8999)
h_numu_sig_foundVtx.GetXaxis().SetTitle("reconstructed neutrino energy (GeV)")
h_numu_sig_foundVtx.GetXaxis().CenterTitle(True)
h_numu_sig_foundVtx.GetYaxis().SetTitle("events per 4.4e+19 POT")
h_numu_sig_foundVtx.SetTitle("Selected Inclusive CC #nu_{#mu} Signal Predictions")

h_numu_bkg_foundVtx.GetXaxis().SetRangeUser(0,1.8999)
h_numu_bkg_foundVtx.GetXaxis().SetTitle("reconstructed neutrino energy (GeV)")
h_numu_bkg_foundVtx.GetXaxis().CenterTitle(True)
h_numu_bkg_foundVtx.GetYaxis().SetTitle("events per 4.4e+19 POT")
h_numu_bkg_foundVtx.SetTitle("Selected Inclusive CC #nu_{#mu} Background Predictions")

h_nue_eff_foundVtx.SetLineColor(4)
h_nue_eff_foundVtx.SetLineWidth(2)
h_nue_eff_foundNuVtx.SetLineColor(8)
h_nue_eff_foundNuVtx.SetLineWidth(2)
h_nue_eff_noMu.SetLineColor(1)
h_nue_eff_noMu.SetLineWidth(2)
h_nue_eff_primEl.SetLineColor(28)
h_nue_eff_primEl.SetLineWidth(2)
h_nue_eff_noMuLike.SetLineColor(38)
h_nue_eff_noMuLike.SetLineWidth(2)
h_nue_eff_allCuts.SetLineColor(2)
h_nue_eff_allCuts.SetLineWidth(2)

hT_nue_eff_foundVtx.SetLineColor(4)
hT_nue_eff_foundVtx.SetLineWidth(2)
hT_nue_eff_foundNuVtx.SetLineColor(8)
hT_nue_eff_foundNuVtx.SetLineWidth(2)
hT_nue_eff_noMu.SetLineColor(1)
hT_nue_eff_noMu.SetLineWidth(2)
hT_nue_eff_primEl.SetLineColor(28)
hT_nue_eff_primEl.SetLineWidth(2)
hT_nue_eff_noMuLike.SetLineColor(38)
hT_nue_eff_noMuLike.SetLineWidth(2)
hT_nue_eff_allCuts.SetLineColor(2)
hT_nue_eff_allCuts.SetLineWidth(2)

h_nue_pur_foundVtx.SetLineColor(4)
h_nue_pur_foundVtx.SetLineWidth(3)
h_nue_pur_foundNuVtx.SetLineColor(8)
h_nue_pur_foundNuVtx.SetLineWidth(2)
h_nue_pur_noMu.SetLineColor(1)
h_nue_pur_noMu.SetLineWidth(2)
h_nue_pur_primEl.SetLineColor(28)
h_nue_pur_primEl.SetLineWidth(2)
h_nue_pur_noMuLike.SetLineColor(38)
h_nue_pur_noMuLike.SetLineWidth(2)
h_nue_pur_allCuts.SetLineColor(2)
h_nue_pur_allCuts.SetLineWidth(2)

h_numu_eff_foundVtx.SetLineColor(4)
h_numu_eff_foundVtx.SetLineWidth(2)
h_numu_eff_foundNuVtx.SetLineColor(8)
h_numu_eff_foundNuVtx.SetLineWidth(2)
h_numu_eff_allCuts.SetLineColor(2)
h_numu_eff_allCuts.SetLineWidth(2)

hT_numu_eff_foundVtx.SetLineColor(4)
hT_numu_eff_foundVtx.SetLineWidth(2)
hT_numu_eff_foundNuVtx.SetLineColor(8)
hT_numu_eff_foundNuVtx.SetLineWidth(2)
hT_numu_eff_allCuts.SetLineColor(2)
hT_numu_eff_allCuts.SetLineWidth(2)

h_numu_pur_foundVtx.SetLineColor(4)
h_numu_pur_foundVtx.SetLineWidth(2)
h_numu_pur_foundNuVtx.SetLineColor(8)
h_numu_pur_foundNuVtx.SetLineWidth(2)
h_numu_pur_allCuts.SetLineColor(2)
h_numu_pur_allCuts.SetLineWidth(2)

h_nue_sig_noCuts.SetLineColor(30)
h_nue_sig_noCuts.SetLineWidth(2)
h_nue_sig_foundVtx.SetLineColor(4)
h_nue_sig_foundVtx.SetLineWidth(2)
h_nue_sig_foundNuVtx.SetLineColor(8)
h_nue_sig_foundNuVtx.SetLineWidth(2)
h_nue_sig_noMu.SetLineColor(1)
h_nue_sig_noMu.SetLineWidth(2)
h_nue_sig_primEl.SetLineColor(28)
h_nue_sig_primEl.SetLineWidth(2)
h_nue_sig_noMuLike.SetLineColor(38)
h_nue_sig_noMuLike.SetLineWidth(2)
h_nue_sig_allCuts.SetLineColor(2)
h_nue_sig_allCuts.SetLineWidth(2)

h_nue_bkg_foundVtx.SetLineColor(4)
h_nue_bkg_foundVtx.SetLineWidth(2)
h_nue_bkg_foundNuVtx.SetLineColor(8)
h_nue_bkg_foundNuVtx.SetLineWidth(2)
h_nue_bkg_noMu.SetLineColor(1)
h_nue_bkg_noMu.SetLineWidth(2)
h_nue_bkg_primEl.SetLineColor(28)
h_nue_bkg_primEl.SetLineWidth(2)
h_nue_bkg_noMuLike.SetLineColor(38)
h_nue_bkg_noMuLike.SetLineWidth(2)
h_nue_bkg_allCuts.SetLineColor(2)
h_nue_bkg_allCuts.SetLineWidth(2)

h_numu_sig_noCuts.SetLineColor(30)
h_numu_sig_noCuts.SetLineWidth(2)
h_numu_sig_foundVtx.SetLineColor(4)
h_numu_sig_foundVtx.SetLineWidth(2)
h_numu_sig_foundNuVtx.SetLineColor(8)
h_numu_sig_foundNuVtx.SetLineWidth(2)
h_numu_sig_allCuts.SetLineColor(2)
h_numu_sig_allCuts.SetLineWidth(2)

h_numu_bkg_foundVtx.SetLineColor(4)
h_numu_bkg_foundVtx.SetLineWidth(2)
h_numu_bkg_foundNuVtx.SetLineColor(8)
h_numu_bkg_foundNuVtx.SetLineWidth(2)
h_numu_bkg_allCuts.SetLineColor(2)
h_numu_bkg_allCuts.SetLineWidth(2)

nue_foundVtx_pCos = 4082.97/15259.9
nue_foundVtx_pNu = 1.0 - nue_foundVtx_pCos
nue_foundNuVtx_pCos = 1137.92/12165.6
nue_foundNuVtx_pNu = 1.0 - nue_foundNuVtx_pCos
nue_noMu_pCos = 862.219/3756.53
nue_noMu_pNu = 1.0 - nue_noMu_pCos
nue_primEl_pCos = 8.83434/45.9114
nue_primEl_pNu = 1.0 - nue_primEl_pCos
nue_noMuLike_pCos = 6.35502/34.4343
nue_noMuLike_pNu = 1.0 - nue_noMuLike_pCos
nue_allCuts_pCos = 1.13991/4.30218
nue_allCuts_pNu = 1.0 - nue_allCuts_pCos

numu_foundVtx_pCos = 3883.39/5418.81
numu_foundVtx_pNu = 1.0 - numu_foundVtx_pCos
numu_foundNuVtx_pCos = 1009.42/2448.88
numu_foundNuVtx_pNu = 1.0 - numu_foundNuVtx_pCos
numu_allCuts_pCos = 245.789/339.136
numu_allCuts_pNu = 1.0 - numu_allCuts_pCos


outfile = rt.TFile("plot_CCinclusive_selections_efficiency_and_purity_makePlots_output.root","RECREATE")

cnv_CCnue_sig = rt.TCanvas("cnv_CCnue_sig","cnv_CCnue_sig")
cnv_CCnue_sig.SetGrid()
#h_nue_sig_noCuts.Draw("EHIST")
h_nue_sig_foundVtx.Draw("EHIST")
h_nue_sig_foundNuVtx.Draw("EHISTSAME")
h_nue_sig_noMu.Draw("EHISTSAME")
h_nue_sig_primEl.Draw("EHISTSAME")
h_nue_sig_noMuLike.Draw("EHISTSAME")
h_nue_sig_allCuts.Draw("EHISTSAME")
leg_CCnue_sig = rt.TLegend(0.7,0.7,0.9,0.9)
leg_CCnue_sig.AddEntry(h_nue_sig_noCuts, "no cuts (%.2f)"%h_nue_sig_noCuts.Integral(), "")
leg_CCnue_sig.AddEntry(h_nue_sig_foundVtx, "cut 1 (%.2f)"%h_nue_sig_foundVtx.Integral(), "l")
leg_CCnue_sig.AddEntry(h_nue_sig_foundNuVtx, "cuts 1,2 (%.2f)"%h_nue_sig_foundNuVtx.Integral(), "l")
leg_CCnue_sig.AddEntry(h_nue_sig_noMu, "cuts 1-3 (%.2f)"%h_nue_sig_noMu.Integral(), "l")
leg_CCnue_sig.AddEntry(h_nue_sig_primEl, "cuts 1-4 (%.2f)"%h_nue_sig_primEl.Integral(), "l")
leg_CCnue_sig.AddEntry(h_nue_sig_noMuLike, "cuts 1-5 (%.2f)"%h_nue_sig_noMuLike.Integral(), "l")
leg_CCnue_sig.AddEntry(h_nue_sig_allCuts, "all cuts (%.2f)"%h_nue_sig_allCuts.Integral(), "l")
leg_CCnue_sig.Draw()
label_nue_sig = getOverflowLabel(h_nue_sig_noCuts)
#label_nue_defVal_sig = getDefaultValueLabel(h_nue_sig_noCuts, "no reco #nu")
label_nue_sig.Draw()
#label_nue_defVal_sig.Draw()
cnv_CCnue_sig.Write()

cnv_CCnue_bkg = rt.TCanvas("cnv_CCnue_bkg","cnv_CCnue_bkg")
cnv_CCnue_bkg.SetLogy()
cnv_CCnue_bkg.SetGrid()
h_nue_bkg_foundVtx.Draw("EHIST")
h_nue_bkg_foundNuVtx.Draw("EHISTSAME")
h_nue_bkg_noMu.Draw("EHISTSAME")
h_nue_bkg_primEl.Draw("EHISTSAME")
h_nue_bkg_noMuLike.Draw("EHISTSAME")
h_nue_bkg_allCuts.Draw("EHISTSAME")
leg_CCnue_bkg = rt.TLegend(0.7,0.7,0.9,0.9)
leg_CCnue_bkg.AddEntry(h_nue_bkg_foundVtx, "cut 1 (%.2f, %.0f%% neutrino / %.0f%% cosmic)"%(h_nue_bkg_foundVtx.Integral(),nue_foundVtx_pNu*100,nue_foundVtx_pCos*100), "l")
leg_CCnue_bkg.AddEntry(h_nue_bkg_foundNuVtx, "cuts 1,2 (%.2f, %.0f%% neutrino / %.0f%% cosmic)"%(h_nue_bkg_foundNuVtx.Integral(),nue_foundNuVtx_pNu*100,nue_foundNuVtx_pCos*100), "l")
leg_CCnue_bkg.AddEntry(h_nue_bkg_noMu, "cuts 1-3 (%.2f, %.0f%% neutrino / %.0f%% cosmic)"%(h_nue_bkg_noMu.Integral(),nue_noMu_pNu*100,nue_noMu_pCos*100), "l")
leg_CCnue_bkg.AddEntry(h_nue_bkg_primEl, "cuts 1-4 (%.2f, %.0f%% neutrino / %.0f%% cosmic)"%(h_nue_bkg_primEl.Integral(),nue_primEl_pNu*100,nue_primEl_pCos*100), "l")
leg_CCnue_bkg.AddEntry(h_nue_bkg_noMuLike, "cuts 1-5 (%.2f, %.0f%% neutrino / %.0f%% cosmic)"%(h_nue_bkg_noMuLike.Integral(),nue_noMuLike_pNu*100,nue_noMuLike_pCos*100), "l")
leg_CCnue_bkg.AddEntry(h_nue_bkg_allCuts, "all cuts (%.2f, %.0f%% neutrino / %.0f%% cosmic)"%(h_nue_bkg_allCuts.Integral(),nue_allCuts_pNu*100,nue_allCuts_pCos*100), "l")
leg_CCnue_bkg.Draw()
#label_nue_bkg = getOverflowLabel(h_nue_bkg_foundVtx, 0.00001)
#label_nue_bkg.Draw()
cnv_CCnue_bkg.Write()

cnv_CCnue_eff = rt.TCanvas("cnv_CCnue_eff","cnv_CCnue_eff")
cnv_CCnue_eff.SetGrid()
h_nue_eff_foundVtx.Draw("E")
h_nue_eff_foundNuVtx.Draw("ESAME")
h_nue_eff_noMu.Draw("ESAME")
h_nue_eff_primEl.Draw("ESAME")
h_nue_eff_noMuLike.Draw("ESAME")
h_nue_eff_allCuts.Draw("ESAME")
leg_CCnue_eff = rt.TLegend(0.7,0.7,0.9,0.9)
leg_CCnue_eff.AddEntry(h_nue_eff_foundVtx, "cut 1 (overall efficiency: 89%)", "l")
leg_CCnue_eff.AddEntry(h_nue_eff_foundNuVtx, "cuts 1,2 (overall efficiency: 87%)", "l")
leg_CCnue_eff.AddEntry(h_nue_eff_noMu, "cuts 1-3 (overall efficiency: 85%)", "l")
leg_CCnue_eff.AddEntry(h_nue_eff_primEl, "cuts 1-4 (overall efficiency: 72%)", "l")
leg_CCnue_eff.AddEntry(h_nue_eff_noMuLike, "cuts 1-5 (overall efficiency: 68%)", "l")
leg_CCnue_eff.AddEntry(h_nue_eff_allCuts, "all cuts (overall efficiency: 57%)", "l")
leg_CCnue_eff.Draw()
label_nue_eff = getOverflowLabel(h_nue_eff_foundVtx)
label_nue_eff.Draw()
cnv_CCnue_eff.Write()

cnv_CCnue_eff_te = rt.TCanvas("cnv_CCnue_eff_te","cnv_CCnue_eff_te")
cnv_CCnue_eff_te.SetGrid()
hT_nue_eff_foundVtx.Draw("E")
hT_nue_eff_foundNuVtx.Draw("ESAME")
hT_nue_eff_noMu.Draw("ESAME")
hT_nue_eff_primEl.Draw("ESAME")
hT_nue_eff_noMuLike.Draw("ESAME")
hT_nue_eff_allCuts.Draw("ESAME")
leg_CCnue_eff_te = rt.TLegend(0.7,0.7,0.9,0.9)
leg_CCnue_eff_te.AddEntry(hT_nue_eff_foundVtx, "cut 1 (overall efficiency: 89%)", "l")
leg_CCnue_eff_te.AddEntry(hT_nue_eff_foundNuVtx, "cuts 1,2 (overall efficiency: 87%)", "l")
leg_CCnue_eff_te.AddEntry(hT_nue_eff_noMu, "cuts 1-3 (overall efficiency: 85%)", "l")
leg_CCnue_eff_te.AddEntry(hT_nue_eff_primEl, "cuts 1-4 (overall efficiency: 72%)", "l")
leg_CCnue_eff_te.AddEntry(hT_nue_eff_noMuLike, "cuts 1-5 (overall efficiency: 68%)", "l")
leg_CCnue_eff_te.AddEntry(hT_nue_eff_allCuts, "all cuts (overall efficiency: 57%)", "l")
leg_CCnue_eff_te.Draw()
cnv_CCnue_eff_te.Write()

cnv_CCnue_pur = rt.TCanvas("cnv_CCnue_pur","cnv_CCnue_pur")
cnv_CCnue_pur.SetGrid()
h_nue_pur_foundVtx.Draw("E")
h_nue_pur_foundNuVtx.Draw("ESAME")
h_nue_pur_noMu.Draw("ESAME")
h_nue_pur_primEl.Draw("ESAME")
h_nue_pur_noMuLike.Draw("ESAME")
h_nue_pur_allCuts.Draw("ESAME")
leg_CCnue_pur = rt.TLegend(0.7,0.7,0.9,0.9)
leg_CCnue_pur.SetNColumns(2)
leg_CCnue_pur.AddEntry(h_nue_eff_foundVtx, "cut 1 (overall purity: 0.45%)", "l")
leg_CCnue_pur.AddEntry(h_nue_pur_foundNuVtx, "cuts 1,2 (overall purity: 0.55%)", "l")
leg_CCnue_pur.AddEntry(h_nue_pur_noMu, "cuts 1-3 (overall purity: 1.7%)", "l")
leg_CCnue_pur.AddEntry(h_nue_pur_primEl, "cuts 1-4 (overall purity: 55%)", "l")
leg_CCnue_pur.AddEntry(h_nue_pur_noMuLike, "cuts 1-5 (overall purity: 60%)", "l")
leg_CCnue_pur.AddEntry(h_nue_pur_allCuts, "all cuts (overall purity: 91%)", "l")
leg_CCnue_pur.Draw()
label_nue_pur = getOverflowLabel(h_nue_pur_foundVtx)
label_nue_pur.Draw()
cnv_CCnue_pur.Write()

cnv_CCnumu_sig = rt.TCanvas("cnv_CCnumu_sig","cnv_CCnumu_sig")
cnv_CCnumu_sig.SetGrid()
#h_numu_sig_noCuts.Draw("EHIST")
h_numu_sig_foundVtx.Draw("EHIST")
h_numu_sig_foundNuVtx.Draw("EHISTSAME")
h_numu_sig_allCuts.Draw("EHISTSAME")
leg_CCnumu_sig = rt.TLegend(0.7,0.7,0.9,0.9)
leg_CCnumu_sig.AddEntry(h_numu_sig_noCuts, "no cuts (%.2f)"%h_numu_sig_noCuts.Integral(), "")
leg_CCnumu_sig.AddEntry(h_numu_sig_foundVtx, "cut 1 (%.2f)"%h_numu_sig_foundVtx.Integral(), "l")
leg_CCnumu_sig.AddEntry(h_numu_sig_foundNuVtx, "cuts 1,2 (%.2f)"%h_numu_sig_foundNuVtx.Integral(), "l")
leg_CCnumu_sig.AddEntry(h_numu_sig_allCuts, "all cuts (%.2f)"%h_numu_sig_allCuts.Integral(), "l")
leg_CCnumu_sig.Draw()
label_numu_sig = getOverflowLabel(h_numu_sig_noCuts)
label_numu_sig.Draw()
cnv_CCnumu_sig.Write()

cnv_CCnumu_bkg = rt.TCanvas("cnv_CCnumu_bkg","cnv_CCnumu_bkg")
cnv_CCnumu_bkg.SetGrid()
h_numu_bkg_foundVtx.Draw("EHIST")
h_numu_bkg_foundNuVtx.Draw("EHISTSAME")
h_numu_bkg_allCuts.Draw("EHISTSAME")
leg_CCnumu_bkg = rt.TLegend(0.7,0.7,0.9,0.9)
leg_CCnumu_bkg.AddEntry(h_numu_bkg_foundVtx, "cut 1 (%.2f, %.0f%% neutrino / %.0f%% cosmic)"%(h_numu_bkg_foundVtx.Integral(),numu_foundVtx_pNu*100,numu_foundVtx_pCos*100), "l")
leg_CCnumu_bkg.AddEntry(h_numu_bkg_foundNuVtx, "cuts 1,2 (%.2f, %.0f%% neutrino / %.0f%% cosmic)"%(h_numu_bkg_foundNuVtx.Integral(),numu_foundNuVtx_pNu*100,numu_foundNuVtx_pCos*100), "l")
leg_CCnumu_bkg.AddEntry(h_numu_bkg_allCuts, "all cuts (%.2f, %.0f%% neutrino / %.0f%% cosmic)"%(h_numu_bkg_allCuts.Integral(),numu_allCuts_pNu*100,numu_allCuts_pCos*100), "l")
leg_CCnumu_bkg.Draw()
label_numu_bkg = getOverflowLabel(h_numu_bkg_foundVtx)
label_numu_bkg.Draw()
cnv_CCnumu_bkg.Write()

cnv_CCnumu_eff = rt.TCanvas("cnv_CCnumu_eff","cnv_CCnumu_eff")
cnv_CCnumu_eff.SetGrid()
h_numu_eff_foundVtx.Draw("E")
h_numu_eff_foundNuVtx.Draw("ESAME")
h_numu_eff_allCuts.Draw("ESAME")
leg_CCnumu_eff = rt.TLegend(0.7,0.7,0.9,0.9)
leg_CCnumu_eff.AddEntry(h_numu_eff_foundVtx, "cut 1 (overall efficiency: 82%)", "l")
leg_CCnumu_eff.AddEntry(h_numu_eff_foundNuVtx, "cuts 1,2 (overall efficiency: 81%)", "l")
leg_CCnumu_eff.AddEntry(h_numu_eff_allCuts, "all cuts (overall efficiency: 68%)", "l")
leg_CCnumu_eff.Draw()
label_numu_eff = getOverflowLabel(h_numu_eff_foundVtx)
label_numu_eff.Draw()
cnv_CCnumu_eff.Write()

cnv_CCnumu_eff_te = rt.TCanvas("cnv_CCnumu_eff_te","cnv_CCnumu_eff_te")
cnv_CCnumu_eff_te.SetGrid()
hT_numu_eff_foundVtx.Draw("E")
hT_numu_eff_foundNuVtx.Draw("ESAME")
hT_numu_eff_allCuts.Draw("ESAME")
leg_CCnumu_eff_te = rt.TLegend(0.7,0.7,0.9,0.9)
leg_CCnumu_eff_te.AddEntry(hT_numu_eff_foundVtx, "cut 1 (overall efficiency: 82%)", "l")
leg_CCnumu_eff_te.AddEntry(hT_numu_eff_foundNuVtx, "cuts 1,2 (overall efficiency: 81%)", "l")
leg_CCnumu_eff_te.AddEntry(hT_numu_eff_allCuts, "all cuts (overall efficiency: 68%)", "l")
leg_CCnumu_eff_te.Draw()
cnv_CCnumu_eff_te.Write()

cnv_CCnumu_pur = rt.TCanvas("cnv_CCnumu_pur","cnv_CCnumu_pur")
cnv_CCnumu_pur.SetGrid()
h_numu_pur_foundVtx.Draw("E")
h_numu_pur_foundNuVtx.Draw("ESAME")
h_numu_pur_allCuts.Draw("ESAME")
leg_CCnumu_pur = rt.TLegend(0.7,0.7,0.9,0.9)
leg_CCnumu_pur.AddEntry(h_numu_pur_foundVtx, "cut 1 (overall purity: 64%)", "l")
leg_CCnumu_pur.AddEntry(h_numu_pur_foundNuVtx, "cuts 1,2 (overall purity: 80%)", "l")
leg_CCnumu_pur.AddEntry(h_numu_pur_allCuts, "all cuts (overall purity: 96%)", "l")
leg_CCnumu_pur.Draw()
label_numu_pur = getOverflowLabel(h_numu_pur_foundVtx)
label_numu_pur.Draw()
cnv_CCnumu_pur.Write()


cut_arr_nue = array('d',[1,2,3,4,5,6])
eff_arr_nue = array('d',[0.89,0.87,0.85,0.72,0.68,0.57])
pur_arr_nue = array('d',[0.0045,0.0055,0.017,0.55,0.60,0.91])
cut_arr_numu = array('d',[1,2,3])
eff_arr_numu = array('d',[0.82,0.81,0.68])
pur_arr_numu = array('d',[0.64,0.80,0.96])

gr_eff_nue = rt.TGraph(6,cut_arr_nue,eff_arr_nue)
gr_eff_nue.SetName("gr_eff_nue")
gr_pur_nue = rt.TGraph(6,cut_arr_nue,pur_arr_nue)
gr_pur_nue.SetName("gr_pur_nue")
gr_eff_numu = rt.TGraph(3,cut_arr_numu,eff_arr_numu)
gr_eff_numu.SetName("gr_eff_numu")
gr_pur_numu = rt.TGraph(3,cut_arr_numu,pur_arr_numu)
gr_pur_numu.SetName("gr_pur_numu")

gr_eff_nue.SetMarkerStyle(20)
gr_eff_nue.SetMarkerColor(rt.kBlue)
gr_eff_nue.SetLineColor(rt.kBlue)
gr_pur_nue.SetMarkerStyle(22)
gr_eff_numu.SetMarkerStyle(20)
gr_eff_numu.SetMarkerColor(rt.kBlue)
gr_eff_numu.SetLineColor(rt.kBlue)
gr_pur_numu.SetMarkerStyle(22)

gr_nue = rt.TMultiGraph()
gr_nue.Add(gr_eff_nue,"LP")
gr_nue.Add(gr_pur_nue,"LP")
gr_nue.SetTitle("Inclusive CC #nu_{e} Selection Efficiency and Purity Predictions")
gr_numu = rt.TMultiGraph()
gr_numu.Add(gr_eff_numu,"LP")
gr_numu.Add(gr_pur_numu,"LP")
gr_numu.SetTitle("Inclusive CC #nu_{#mu} Selection Efficiency and Purity Predictions")

cnv_CCnue_sum = rt.TCanvas("cnv_CCnue_sum","cnv_CCnue_sum")
cnv_CCnue_sum.SetGrid()
gr_nue.Draw("A")
gr_nue.GetXaxis().SetTitle("included cuts")
gr_nue.GetXaxis().SetNdivisions(6)
gr_nue.GetXaxis().CenterTitle(True)
xax_nue = gr_nue.GetXaxis()
cutLabels_nue = ["1","1,2","1-3","1-4","1-5","all"]
for i in range(1,7):
  iB = xax_nue.FindBin(i)
  xax_nue.SetBinLabel(iB, cutLabels_nue[i-1])
rt.gPad.Modified()
rt.gPad.Update()
xax_nue.LabelsOption('u')
xax_nue.SetLabelSize(0.048)
xax_nue.SetLabelOffset(0.008)
xax_nue.SetTitleOffset(1.2)
leg_nue_sum = rt.TLegend(0.7,0.7,0.9,0.9)
leg_nue_sum.AddEntry(gr_eff_nue, "efficiency", "lp")
leg_nue_sum.AddEntry(gr_pur_nue, "purity", "lp")
leg_nue_sum.Draw()
cnv_CCnue_sum.Write()

cnv_CCnumu_sum = rt.TCanvas("cnv_CCnumu_sum","cnv_CCnumu_sum")
cnv_CCnumu_sum.SetGrid()
gr_numu.Draw("A")
gr_numu.GetXaxis().SetTitle("included cuts")
gr_numu.GetXaxis().SetNdivisions(3)
gr_numu.GetXaxis().CenterTitle(True)
xax_numu = gr_numu.GetXaxis()
cutLabels_numu = ["1","1,2","all"]
for i in range(1,4):
  iB = xax_numu.FindBin(i)
  xax_numu.SetBinLabel(iB, cutLabels_numu[i-1])
rt.gPad.Modified()
rt.gPad.Update()
xax_numu.LabelsOption('u')
xax_numu.SetLabelSize(0.048)
xax_numu.SetLabelOffset(0.008)
xax_numu.SetTitleOffset(1.2)
leg_numu_sum = rt.TLegend(0.7,0.7,0.9,0.9)
leg_numu_sum.AddEntry(gr_eff_numu, "efficiency", "lp")
leg_numu_sum.AddEntry(gr_pur_numu, "purity", "lp")
leg_numu_sum.Draw()
cnv_CCnumu_sum.Write()



