#!/bin/bash

./calculate_detvar_systematics_CCnumu_vertex_efficiency.exe -v LYDown -o systematics/detvar/CCnumu_vertex_efficiency_test/calculate_detvar_systematics_CCnumu_vertex_efficiency_LYDown_output.root
./calculate_detvar_systematics_CCnumu_vertex_efficiency.exe -v LYRayleigh -o systematics/detvar/CCnumu_vertex_efficiency_test/calculate_detvar_systematics_CCnumu_vertex_efficiency_LYRayleigh_output.root
./calculate_detvar_systematics_CCnumu_vertex_efficiency.exe -v LYAtt -o systematics/detvar/CCnumu_vertex_efficiency_test/calculate_detvar_systematics_CCnumu_vertex_efficiency_LYAtt_output.root
./calculate_detvar_systematics_CCnumu_vertex_efficiency.exe -v SCE -o systematics/detvar/CCnumu_vertex_efficiency_test/calculate_detvar_systematics_CCnumu_vertex_efficiency_SCE_output.root
./calculate_detvar_systematics_CCnumu_vertex_efficiency.exe -v recomb2 -o systematics/detvar/CCnumu_vertex_efficiency_test/calculate_detvar_systematics_CCnumu_vertex_efficiency_recomb2_output.root
./calculate_detvar_systematics_CCnumu_vertex_efficiency.exe -v wiremodX -o systematics/detvar/CCnumu_vertex_efficiency_test/calculate_detvar_systematics_CCnumu_vertex_efficiency_wiremodX_output.root
./calculate_detvar_systematics_CCnumu_vertex_efficiency.exe -v wiremodYZ -o systematics/detvar/CCnumu_vertex_efficiency_test/calculate_detvar_systematics_CCnumu_vertex_efficiency_wiremodYZ_output.root
./calculate_detvar_systematics_CCnumu_vertex_efficiency.exe -v wiremodThetaXZ -o systematics/detvar/CCnumu_vertex_efficiency_test/calculate_detvar_systematics_CCnumu_vertex_efficiency_wiremodThetaXZ_output.root
./calculate_detvar_systematics_CCnumu_vertex_efficiency.exe -v wiremodThetaYZ -o systematics/detvar/CCnumu_vertex_efficiency_test/calculate_detvar_systematics_CCnumu_vertex_efficiency_wiremodThetaYZ_output.root
