#!/bin/bash

./calculate_detvar_systematics_CCnumu_particle_score_shifts.exe -v LYDown -o systematics/detvar/CCnumu_particle_score_shifts_test/calculate_detvar_systematics_CCnumu_particle_score_shifts_LYDown_output.root
./calculate_detvar_systematics_CCnumu_particle_score_shifts.exe -v LYRayleigh -o systematics/detvar/CCnumu_particle_score_shifts_test/calculate_detvar_systematics_CCnumu_particle_score_shifts_LYRayleigh_output.root
./calculate_detvar_systematics_CCnumu_particle_score_shifts.exe -v LYAtt -o systematics/detvar/CCnumu_particle_score_shifts_test/calculate_detvar_systematics_CCnumu_particle_score_shifts_LYAtt_output.root
./calculate_detvar_systematics_CCnumu_particle_score_shifts.exe -v SCE -o systematics/detvar/CCnumu_particle_score_shifts_test/calculate_detvar_systematics_CCnumu_particle_score_shifts_SCE_output.root
./calculate_detvar_systematics_CCnumu_particle_score_shifts.exe -v recomb2 -o systematics/detvar/CCnumu_particle_score_shifts_test/calculate_detvar_systematics_CCnumu_particle_score_shifts_recomb2_output.root
./calculate_detvar_systematics_CCnumu_particle_score_shifts.exe -v wiremodX -o systematics/detvar/CCnumu_particle_score_shifts_test/calculate_detvar_systematics_CCnumu_particle_score_shifts_wiremodX_output.root
./calculate_detvar_systematics_CCnumu_particle_score_shifts.exe -v wiremodYZ -o systematics/detvar/CCnumu_particle_score_shifts_test/calculate_detvar_systematics_CCnumu_particle_score_shifts_wiremodYZ_output.root
./calculate_detvar_systematics_CCnumu_particle_score_shifts.exe -v wiremodThetaXZ -o systematics/detvar/CCnumu_particle_score_shifts_test/calculate_detvar_systematics_CCnumu_particle_score_shifts_wiremodThetaXZ_output.root
./calculate_detvar_systematics_CCnumu_particle_score_shifts.exe -v wiremodThetaYZ -o systematics/detvar/CCnumu_particle_score_shifts_test/calculate_detvar_systematics_CCnumu_particle_score_shifts_wiremodThetaYZ_output.root
